const ref=name=>({$ref:'#/components/schemas/'+name});
const string={type:'string'},uuid={type:'string',format:'uuid'},hash={type:'string',pattern:'^[a-f0-9]{64}$'},time={type:['integer','null'],description:'Unix milliseconds; null means not verified/absent.'};
const object=(properties,required=Object.keys(properties),additionalProperties=false)=>({type:'object',properties,required,additionalProperties});
const enumeration=values=>({type:'string',enum:values.split(' ')});
const response=(schema,description='Success')=>({description,content:{'application/json':{schema}}});
const request=schema=>({required:true,content:{'application/json':{schema}}});
export function openstrudelOpenAPI(origin) {
  const schemas={
    Error:object({error:string,code:{type:['string','null']},request_id:uuid}),
    OAuthError:object({error:string,error_description:string}),
    Profile:object({id:{const:'openstrudel-home-v1'},version:{const:1},region:string,ram_mb:{const:4096},disk_gb:{const:30},cpu:{const:'1A'},public_ipv4:{const:1},traffic_gb:{const:5000},os:{const:'Ubuntu 24.04 LTS'},image:{type:['string','null']},release_url:{type:'string',format:'uri'},release_sha256:hash,recipe_sha256:hash}),
    QuoteRequest:object({profile_id:{const:'openstrudel-home-v1'},payment_method:enumeration('card crypto test'),platform:enumeration('mac web ios'),installation_id:uuid},['profile_id','payment_method','platform']),
    Quote:object({quote_id:uuid,quote_digest:hash,profile:ref('Profile'),platform:enumeration('mac web'),kind:enumeration('initial renewal'),installation_id:{type:['string','null'],format:'uuid'},payment_method:enumeration('card crypto test'),amount_minor:{type:'integer',minimum:1},currency:enumeration('USD USDT'),currency_exponent:{const:2},total_is_final:{const:true},tax_note:string,period_days:{const:30},starts_at:enumeration('current_period_end_or_payment verified_home_ready'),automatic_renewal:{const:false},grace_days:{const:3},cancellation:string,refund_policy:string,created_at:time,expires_at:time,checkout_deadline:time,mode:enumeration('emulator live')}),
    Bootstrap:object({installationId:uuid,privateKeyPEM:{type:'string',maxLength:4096,writeOnly:true,description:'P-256 PKCS8 PEM; only over authenticated TLS; encrypted until verified installation. Never send owner token.'},ownerTokenHash:hash}),
    OrderRequest:object({quote_id:uuid,quote_digest:hash,idempotency_key:{type:'string',pattern:'^[-a-zA-Z0-9_]{8,100}$'},consent:{const:true},bootstrap:ref('Bootstrap'),return_uri:{type:'string',format:'uri',description:'Exact registered callback. Default openstrudel://checkout/wai-vds; no query, fragment or userinfo.'},return_state:{type:'string',pattern:'^[A-Za-z0-9._~-]{16,128}$'}},['quote_id','quote_digest','idempotency_key','consent','return_uri','return_state']),
    Order:object({order_id:uuid,installation_id:uuid,quote_id:uuid,quote_digest:hash,order_status:enumeration('draft checkout paid fulfilling fulfilled needs_refund refunded canceled'),kind:enumeration('initial renewal'),amount_minor:{type:'integer'},currency:enumeration('USD USDT'),currency_exponent:{const:2},payment_method:enumeration('card crypto test'),payment_state:enumeration('unpaid pending unknown failed partially_paid paid partially_refunded refunded refund_review additional_payment_review'),session_state:enumeration('none open unknown expired canceled closed review confirmation_pending'),action_required:enumeration('start_payment retry_payment wait_for_confirmation contact_support wait_for_home claim_connection complete_payment none new_quote_required purchase_unavailable'),session_expires_at:time,payment_verified_at:time,provisioning_state:enumeration('not_started paid creating configuring checking ready overdue rejected unknown attention deleting deleted'),home_state:enumeration('pending installing ready attention canceled deleted'),paid_until:time,cancel_at_end:{type:'boolean'},readiness_verified_at:time,mode:enumeration('emulator live'),created_at:time}),
    Checkout:{...object({type:{const:'hosted'},url:{type:['string','null'],format:'uri'},...{}},['type','url'],true),description:'Order fields plus type=hosted and nullable URL. Open only when action_required=complete_payment. Never infer payment from return navigation.'},
    ClaimRequest:object({recover_owner:{type:'boolean',default:false,description:'Issue existing Home owner-pairing invitation; requires auth_time within 5 minutes.'}},[]),
    Claim:object({claim_token:{...hash,writeOnly:false},installation_id:uuid,expires_in:{const:300}}),
    ConsumeClaim:object({claim_token:hash,installation_id:uuid}),
    Pairing:object({host:string,port:{const:7789},certificate_sha256:hash,invitation_key:hash,expires_at:time,path:{const:'/pair'},method:{const:'POST'},authorization:{const:'Bearer invitation_key'},emulated:{type:'boolean'}},['host','port','certificate_sha256','invitation_key','expires_at','path','method','authorization']),
    Connection:object({installation_id:uuid,url:{type:'string',format:'uri'},certificate_sha256:hash,release_sha256:hash,owner_token_source:enumeration('device_keychain home_pairing'),openai_action:{const:'owner_sign_in_on_home'},mode:enumeration('emulator kamatera'),pairing:ref('Pairing')},['installation_id','url','certificate_sha256','release_sha256','owner_token_source','openai_action','mode']),
    Credentials:object({access_token:string,token_type:{const:'Bearer'},expires_in:{const:900},refresh_token:string,refresh_expires_in:{type:'integer'},scope:{const:'home:manage'}}),
    TokenRequest:{oneOf:[object({grant_type:{const:'authorization_code'},client_id:{const:'openstrudel'},code:hash,code_verifier:{type:'string',pattern:'^[A-Za-z0-9._~-]{43,128}$'},redirect_uri:{type:'string',format:'uri'}}),object({grant_type:{const:'refresh_token'},client_id:{const:'openstrudel'},refresh_token:string})]},
    Access:object({installation_id:uuid,ip:string,ssh:string,host_key:string,private_key:{type:'string',description:'Secret response body. Requires fresh OAuth login. Never put in a URL or log.'}}),
    Export:object({installation_id:uuid,type:{const:'manual_ssh'},contains_secrets:{const:true},temporary_home_stop:{const:true},instruction:string,command:string,stdin_script:string}),
    Catalog:object({client_id:{const:'openstrudel'},profile:ref('Profile'),purchase_enabled:{type:'boolean'},availability_reason:{type:['string','null']},payment_methods:{type:'array',items:object({id:enumeration('card crypto test'),currency:enumeration('USD USDT'),amount_minor:{type:['integer','null']},currency_exponent:{const:2}})},checkout:object({type:{const:'hosted'},embedded:{const:false},provider:{const:'WAI Pay'},return_to:{const:'OpenStrudel'}}),platforms:object({mac:object({purchase_enabled:{type:'boolean'}}),web:object({purchase_enabled:{type:'boolean'}}),ios:object({purchase_enabled:{const:false},mode:{const:'join_by_invitation'}})}),automatic_renewal:{const:false},period_days:{const:30},grace_days:{const:3},openai:{const:'owner_signs_in_on_home'},mode:enumeration('emulator live_gated')})
  };
  schemas.Checkout=object({...schemas.Order.properties,type:{const:'hosted'},url:{type:['string','null'],format:'uri'}});
  const paths={};
  const add=(path,method,id,schema,{body,status=200,publicRoute=false,description=''}={})=>{
    const parameters=[...path.matchAll(/\{(.*?)\}/g)].map(m=>({in:'path',name:m[1],required:true,schema:uuid}));
    paths[path]||={};paths[path][method]={operationId:id,description,security:publicRoute?[]:[{nativeOwner:[]}],...(parameters.length?{parameters}:{}),...(body?{requestBody:request(body)}:{}),responses:{[status]:response(schema),'400':response(ref('Error'),'Invalid request'),'401':response(ref('Error'),'Owner login required'),'403':response(ref('Error'),'Fresh login or platform/origin restriction'),'404':response(ref('Error'),'Not found for this owner'),'409':response(ref('Error'),'Saved state conflicts with requested action'),'429':response(ref('Error'),'Rate limited'),'503':response(ref('Error'),'Unavailable; retain order and retry status')}};
  };
  const p='/api/v2/openstrudel';
  add(p+'/catalog','get','getCatalog',ref('Catalog'),{publicRoute:true});
  add(p+'/quotes','post','createQuote',ref('Quote'),{body:ref('QuoteRequest'),status:201,description:'Immutable 15-minute quote. Same VM renewal uses installation_id; no bootstrap for renewal. iOS purchase rejected.'});
  add(p+'/orders','post','createOrder',ref('Order'),{body:ref('OrderRequest'),status:201,description:'Initial requires bootstrap; renewal forbids it. Same owner + idempotency key + identical payload always returns same order, even after quote expiry. Changed payload =>409.'});
  add(p+'/orders','get','listOwnOrders',object({orders:{type:'array',items:ref('Order')}}));
  add(p+'/orders/{order_id}','get','getOwnOrder',ref('Order'));
  add(p+'/orders/{order_id}/checkout','post','checkout',ref('Checkout'),{description:'Hosted WAI Pay fallback. Sync before checkout; resume same unknown payment attempt. Never request a new order on network failure.'});
  add(p+'/orders/{order_id}/sync','post','syncPayment',ref('Order'),{description:'Authenticated gateway read only; no new invoice or charge.'});
  add(p+'/orders/{order_id}/abandon','post','abandonUnpaidOrder',ref('Order'),{description:'Only before invoice or after verified unpaid expiry/cancellation. Unknown or partly paid attempts cannot be abandoned.'});
  add(p+'/installations/{installation_id}/claims','post','issueConnectionClaim',ref('Claim'),{body:ref('ClaimRequest'),status:201});
  add(p+'/claims/consume','post','consumeConnectionClaim',ref('Connection'),{body:ref('ConsumeClaim'),description:'Five minutes, one use, bound to owner, grant and installation. No credentials in redirects. Recovery consumes the claim before requesting a Home invitation; on uncertain response issue a new claim.'});
  add(p+'/installations/{installation_id}/cancellation','post','setCancellation',ref('Order'),{body:object({cancel_at_end:{type:'boolean'}})});
  add(p+'/installations/{installation_id}/access','post','rootAccess',ref('Access'),{description:'Requires fresh login (prompt=login); refresh does not reset auth_time.'});
  add(p+'/installations/{installation_id}/export','post','exportInstructions',ref('Export'),{description:'Owner-run SSH export, with a brief Home stop and automatic restart. Does not create an archive or execute commands on this request. Requires fresh login.'});
  add(p+'/installations/{installation_id}/delete','post','deleteInstallation',ref('Order'),{body:object({confirm:uuid}),description:'Explicit installation ID confirmation and fresh login. Deletion is asynchronous and separately verified.'});
  add('/oauth/token','post','exchangeCodeOrRefresh',ref('Credentials'),{body:ref('TokenRequest'),publicRoute:true});
  paths['/oauth/token'].post.requestBody.content['application/x-www-form-urlencoded']={schema:ref('TokenRequest')};
  paths['/oauth/token'].post.responses['400']=response(ref('OAuthError'),'OAuth exchange rejected');
  add('/oauth/revoke','post','revokeCurrentGrant',object({ok:{const:true}}));
  paths['/oauth/authorize']={get:{operationId:'authorizeOwner',security:[],description:'Open in system browser. Short OpenStrudel login. Default exact redirect openstrudel://oauth/wai-vds. Returns code, state and issuer; codes expire in 120 seconds. Public client; no secret. Login/create/recovery is hosted on this origin.',parameters:Object.entries({client_id:{const:'openstrudel'},response_type:{const:'code'},redirect_uri:{type:'string',format:'uri'},state:{type:'string',pattern:'^[A-Za-z0-9._~-]{16,128}$'},code_challenge:{type:'string',pattern:'^[A-Za-z0-9_-]{43}$'},code_challenge_method:{const:'S256'},scope:{const:'home:manage'},prompt:enumeration('login consent')}).map(([name,schema])=>({name,in:'query',required:!['scope','prompt'].includes(name),schema})),responses:{200:{description:'Branded owner login HTML'},400:response(ref('Error'),'Invalid OAuth request')}}};
  return {openapi:'3.1.0',info:{title:'OpenStrudel cloud backend',version:'2.0.0',description:'Production preview. Home purchases remain closed until a separately approved real 4/30 VM and payment acceptance. No shared production API key. Millisecond timestamps; USD/USDT quote amounts both have exponent 2. iOS joins existing teams only.'},servers:[{url:origin}],paths,components:{securitySchemes:{nativeOwner:{type:'http',scheme:'bearer',description:'Opaque short-lived OAuth owner token, not a WAI API key.'}},schemas}};
}
