import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync,mkdtempSync,rmSync } from 'node:fs';
import { resolve } from 'node:path';
import { Service,config } from '../src/service.mjs';
import { webhookSignature } from '../src/security.mjs';

function fixture(t,fetcher) {mkdirSync('work/test-runs',{recursive:true});const dir=mkdtempSync(resolve('work/test-runs/stripe-'));const c=config({WAI_DATA:dir,WAI_PAYMENTS:'stripe_test',WAI_STRIPE_SECRET_KEY:'sk_test_fixture',WAI_STRIPE_WEBHOOK_SECRET:'whsec_fixture'}),s=new Service(c,{fetcher});const a=s.register('stripe@example.test','StripeTestPasswordOnly!','fixture');const o=s.order(a.user.id,{purpose:'clean',consent:true,idempotency_key:'stripe-test-order'});t.after(()=>{s.db.close();rmSync(dir,{recursive:true,force:true});});return {s,a,o};}
test('Stripe hosted checkout request never collects card data and has stable idempotency',async t=>{const calls=[];const {s,a,o}=fixture(t,async(url,options)=>{calls.push({url,options});return Response.json({id:'cs_test_fixture',url:'https://checkout.stripe.com/c/pay/cs_test_fixture'});});await s.checkout(a.user.id,o.id);await s.checkout(a.user.id,o.id);assert.equal(calls.length,1);const {url,options}=calls[0],b=new URLSearchParams(options.body);assert.equal(url,'https://api.stripe.com/v1/checkout/sessions');assert.equal(options.headers['Idempotency-Key'],'wai-vds-checkout-'+o.id);assert.equal(b.get('metadata[user_id]'),a.user.id);assert.equal(b.get('metadata[order_id]'),o.id);assert.equal(b.get('line_items[0][price_data][unit_amount]'),'1200');assert.equal(b.get('payment_method_types[0]'),'card');assert.equal(options.redirect,'error');assert(!options.body.includes('card_number'));});
test('Stripe timeout retains intention; retry sends same key; old uncertain request is blocked',async t=>{const keys=[];let fail=true;const {s,a,o}=fixture(t,async(url,opts)=>{keys.push(opts.headers['Idempotency-Key']);if(fail)throw Error('timeout');return Response.json({id:'cs_test_2',url:'https://checkout.stripe.com/c/pay/cs_test_2'});});await assert.rejects(()=>s.checkout(a.user.id,o.id));assert.equal(s.db.get('SELECT state FROM payments').state,'submitting');fail=false;await s.checkout(a.user.id,o.id);assert.equal(new Set(keys).size,1);s.db.run('UPDATE payments SET url=NULL,created=?',s.now()-24*3600e3);await assert.rejects(()=>s.checkout(a.user.id,o.id),/сверки/);assert.equal(keys.length,2);});
test('Stripe event is corroborated through actual REST lookup before fulfillment',async t=>{const gets=[];let checkout;const {s,a,o}=fixture(t,async(url,options)=>{if(options.method==='POST')return Response.json({id:'cs_test_verified',url:'https://checkout.stripe.com/c/pay/cs_test_verified'});gets.push(url);return Response.json(checkout);});await s.checkout(a.user.id,o.id);checkout={id:'cs_test_verified',client_reference_id:a.user.id,metadata:{user_id:a.user.id,order_id:o.id},amount_total:1200,currency:'usd',livemode:false,mode:'payment',payment_status:'paid'};const e={id:'evt_stripe_verified',type:'checkout.session.completed',livemode:false,data:{object:checkout}},raw=JSON.stringify(e);await s.payments.webhook(raw,webhookSignature(raw,'whsec_fixture'));assert.equal(gets.length,1);assert.match(gets[0],/checkout\/sessions\/cs_test_verified$/);assert.equal(s.db.get('SELECT count(*) n FROM servers').n,1);});
test('Stripe lookup mode mismatch rejects signed event',async t=>{let checkout;const {s,a,o}=fixture(t,async(url,options)=>Response.json(options.method==='POST'?{id:'cs_test_mismatch',url:'https://checkout.stripe.com/c/pay/cs_test_mismatch'}:{...checkout,livemode:true}));await s.checkout(a.user.id,o.id);checkout={id:'cs_test_mismatch',client_reference_id:a.user.id,metadata:{user_id:a.user.id,order_id:o.id},amount_total:1200,currency:'usd',livemode:false,mode:'payment',payment_status:'paid'};const raw=JSON.stringify({id:'evt_mode',type:'checkout.session.completed',livemode:false,data:{object:checkout}});await assert.rejects(()=>s.payments.webhook(raw,webhookSignature(raw,'whsec_fixture')),/не совпадают/);assert.equal(s.db.get('SELECT count(*) n FROM servers').n,0);});
test('temporary unpaid lookup returns retryable error; identical signed success later fulfills',async t=>{let checkout,isPaid=false;const {s,a,o}=fixture(t,async(url,opt)=>Response.json(opt.method==='POST'?{id:'cs_test_eventual',url:'https://checkout.stripe.com/c/pay/cs_test_eventual'}:{...checkout,payment_status:isPaid?'paid':'unpaid'}));await s.checkout(a.user.id,o.id);checkout={id:'cs_test_eventual',client_reference_id:a.user.id,metadata:{user_id:a.user.id,order_id:o.id},amount_total:1200,currency:'usd',livemode:false,mode:'payment',payment_status:'paid'};const raw=JSON.stringify({id:'evt_eventual',type:'checkout.session.completed',livemode:false,data:{object:checkout}}),sig=webhookSignature(raw,'whsec_fixture');await assert.rejects(()=>s.payments.webhook(raw,sig),e=>e.status===503);assert.equal(s.db.get('SELECT count(*) n FROM payment_events').n,0);isPaid=true;await s.payments.webhook(raw,sig);await s.payments.webhook(raw,sig);assert.equal(s.db.get('SELECT count(*) n FROM servers').n,1);});
test('verified expiry rotates checkout generation on the same order with a new idempotency key',async t=>{let checkout,n=0;const keys=[];const {s,a,o}=fixture(t,async(url,opt)=>{if(opt.method==='POST'){keys.push(opt.headers['Idempotency-Key']);n++;return Response.json({id:'cs_test_gen_'+n,url:'https://checkout.stripe.com/c/pay/cs_test_gen_'+n});}return Response.json(checkout);});await s.checkout(a.user.id,o.id);checkout={id:'cs_test_gen_1',client_reference_id:a.user.id,metadata:{user_id:a.user.id,order_id:o.id},amount_total:1200,currency:'usd',livemode:false,mode:'payment',status:'expired',payment_status:'unpaid'};const raw=JSON.stringify({id:'evt_expired',type:'checkout.session.expired',livemode:false,data:{object:checkout}});await s.payments.webhook(raw,webhookSignature(raw,'whsec_fixture'));await s.checkout(a.user.id,o.id);assert.equal(n,2);assert.equal(keys[1],keys[0]+'_g1');assert.equal(s.db.get('SELECT count(*) n FROM orders').n,1);assert.equal(s.db.get('SELECT generation FROM payments').generation,1);});
test('lost expiry webhook recovers from server-to-server checkout status',async t=>{let checkout,n=0;const {s,a,o}=fixture(t,async(url,opt)=>{if(opt.method==='POST'){n++;return Response.json({id:'cs_test_lost_'+n,url:'https://checkout.stripe.com/c/pay/cs_test_lost_'+n});}return Response.json(checkout);});await s.checkout(a.user.id,o.id);checkout={id:'cs_test_lost_1',metadata:{user_id:a.user.id,order_id:o.id},livemode:false,status:'expired',payment_status:'unpaid'};s.db.run('UPDATE payments SET created=?',s.now()-24*3600e3);await s.checkout(a.user.id,o.id);assert.equal(n,2);assert.equal(s.db.get('SELECT generation FROM payments').generation,1);});
